# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-22.04'
  strategy:
    matrix:
      Python310:
        python.version: '3.11'
        CC: gcc-12
        CXX: g++-12

  steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install numpy scipy meshio cython
    displayName: 'Install dependencies'

  - script: |
      chmod +x build_linux.sh
      ./build_linux.sh
    displayName: 'build'

  - script: |
      ./src/radarsimc/build/radarsimc_test
    displayName: 'gtest'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

- job: Windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python310:
        python.version: '3.11'

  steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install numpy scipy meshio cython
    displayName: 'Install dependencies'

  - script: |
      .\build_win.bat
    displayName: 'build'

  - script: |
      .\src\radarsimc\build\Release\radarsimc_test.exe
    displayName: 'gtest'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'
