name: Windows x86_64 Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Remove OpenSSH
        run: Remove-WindowsCapability -Online -Name OpenSSH.Client
      - name: Chocolatey Action
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: install openssh --pre
      - name: Refresh Env
        run: |
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          refreshenv
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.RADARSIMC}}
          submodules: true
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        run: |
          .\build_win.bat --tier standard --arch cpu --test off
      - name: Test with Google Test
        run: |
          .\src\radarsimcpp\build\Release\radarsimcpp_test.exe
      - name: Test with pytest
        run: |
          pytest
