# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MacOS Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        c_compiler: [gcc-12]
        cxx_compiler: [g++-12]

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RADARSIMC }}
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest numpy scipy pymeshlab cython setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build
        env:
          CC: ${{ matrix.c_compiler }}
          CXX: ${{ matrix.cxx_compiler }}
        run: |
          chmod +x build_macos.sh
          ./build_macos.sh
      - name: Test with Google Test
        run: |
          ./src/radarsimcpp/build/radarsimcpp_test
      - name: Test with pytest
        run: |
          pytest
