# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        c_compiler: [gcc-12]
        cxx_compiler: [g++-12]

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.RADARSIMC }}
        repository: rookiepeng/radarsimc
  
